export const test = {
  id: 1,
  title: 'Trainspottin Exam',
  description: 'This is an exam about the movie Trainspottin',
  questions: [
    {
      id: 1,
      type: 'multiple',
      question: 'Who is the director of the movie?',
      options: [
        { id: 1, text: 'Danny Boyle', isCorrect: true },
        { id: 2, text: 'Quentin Tarantino', isCorrect: false },
        { id: 3, text: 'Steven Spielberg', isCorrect: false },
        { id: 4, text: 'Martin Scorsese', isCorrect: false },
      ],
    },
    {
      id: 2,
      type: 'multiple',
      question: 'Who is the main character?',
      options: [
        { id: 1, text: 'Simon Williamson', isCorrect: false },
        { id: 2, text: 'Daniel Murphy', isCorrect: false },
        { id: 3, text: 'Mark Renton', isCorrect: true },
        { id: 4, text: 'Francis Begbie', isCorrect: false },
      ],
    },
    {
      id: 3,
      type: 'open',
      question: 'What is the choose life spech ?',
      keywords: [
        'choose',
        'life',
        'choose job',
        'choose career',
        'choose family',
        'choose a big television',
        'choose washing machines',
        'choose cars',
        'compact disc players',
        'electrical tin openers',
        'good health',
        'low cholesterol',
        'dental insurance',
        'mortgage',
        'starter home',
        'leisure wear',
        'luggage',
        'three piece suite',
        'DIY',
        'game shows',
        'junk food',
        'children',
        'walks in the park',
        'nine to five',
        'good at golf',
        'washing the car',
        'choice of sweaters',
        'family Christmas',
        'indexed pension',
        'tax exemption',
        'clearing gutters',
        'getting by',
        'looking ahead',
        'the day you die',
      ],
    },
  ],
};
